server:
  port: 8001
spring:
  application:
    name: pool-test
  mail:
    # 下面这个是QQ邮箱host ， 企业邮箱 smtp.exmail.qq.com
    host: smtp.qq.com
  # tencent mail port  这个是固定的
  port: 465
  # 你的QQ邮箱
  username: 1768017757@qq.com
  # 进入邮箱配置后得到的授权码
  password: zqaffdxpmbwjdfdd
  test-connection: true
  properties:
    mail:
      smtp:
        ssl:
          enable: true

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 25
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy


# 动态线程池管理配置
dynamic:
  thread:
    pool:
      config:
        # 状态；true = 开启、false 关闭
        enabled: true
        # redis host
        host: 127.0.0.1
        # redis port
        port: 6379

dynamic-thread-pool:
  alarm:
    enable: true
    use-platform: dingding
    webhook:
      #feishu: https://open.feishu.cn/open-apis/bot/v2/hook/898031bb-892f-4c20-91e4-be92732fa05c
      dingding: 6ff7ae88d03921dc85109541ebdf7a5fb43e700a7851cdf661eff48dae94c4d5